server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: *
  endpoint:
    refresh:
      enabled: true
    health:
      enabled: true
  health:
    db:
      enabled: true        
