server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: amol
    password: 7700#Kpit
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true


management:
  endpoint:
    web:
      base-path: /
    enabled-by-default: false
    health:
      enabled: true
  health:
    db:
      enabled: true
      
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


resilience4j.circuitbreaker:
  instances:
    licenseServiceCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 10000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException$NotFound
    organizationService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60             


resilience4j.bulkhead:
  instances:
    licenseServiceBulkhead:
      maxConcurrentCalls: 20
      maxWaitDuration: 0
    organizationService:
      maxConcurrentCalls: 30
      maxWaitDuration: 0

resilience4j.threadpoolbulkhead:
  instances:
    licenseServiceThreadPoolBulkhead:
      coreThreadPoolSize: 10
      maxThreadPoolSize: 20
      queueCapacity: 30
    organizationService:
      coreThreadPoolSize: 5
      maxThreadPoolSize: 10
      queueCapacity: 20

resilience4j.retry:
  instances:
    licenseServiceRetry:
      maxAttempts: 3
      waitDuration: 5000
      retryExceptions:
        - java.io.IOException
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - org.springframework.web.client.HttpClientErrorException$NotFound
    organizationService:
      maxAttempts: 4
      waitDuration: 2000
      retryExceptions:
        - java.io.IOException
        - org.springframework.web.client.HttpServerErrorException

resilience4j.rateLimiter:
  instances:
    licenseServiceRateLimiter:
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
    organizationService:
      limitForPeriod: 5
      limitRefreshPeriod: 1s
      timeoutDuration: 0                    